-- Catalogue HYDRIC — 40 recettes (10 hydriques, 10 PDJ, 10 déj, 10 dîn)
-- Source: data/hydric_recipes.json

DELETE FROM public.recipes;

INSERT INTO public.recipes (
  id, title, description, day_type, meal_type, duration_min,
  tags, ingredients, steps, plan_required, published
)
VALUES
(
  'c881c1b6-d8d2-487c-8067-83f3e003df80'::uuid,
  'Bouillon détox aux légumes',
  'Léger et réconfortant pour vos jours hydriques',
  'hydric'::day_type,
  NULL::meal_type,
  40,
  ARRAY['cure détox', 'léger', 'chaud'],
  '[{"name":"eau","qty":"2","unit":"L"},{"name":"carottes","qty":"2","unit":"pièces"},{"name":"branche de céleri","qty":"1","unit":"pièce"},{"name":"oignon","qty":"1","unit":"pièce"},{"name":"poireau","qty":"1","unit":"pièce"},{"name":"ail","qty":"3","unit":"gousses"},{"name":"gingembre frais râpé","qty":"1","unit":"c. à soupe"},{"name":"feuille de laurier","qty":"1","unit":"pièce"},{"name":"sel, poivre","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Éplucher et couper grossièrement tous les légumes."},{"step":2,"text":"Les placer dans une grande casserole avec l''eau froide."},{"step":3,"text":"Porter à ébullition puis réduire à feu doux. Laisser mijoter 35 minutes."},{"step":4,"text":"Filtrer le bouillon. Assaisonner et servir chaud dans un bol."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '1ee705af-e2e7-4c7a-8a11-cbd37c6c5e22'::uuid,
  'Tisane gingembre-citron-miel',
  'Boisson réchauffante et anti-inflammatoire pour les matins hydriques',
  'hydric'::day_type,
  NULL::meal_type,
  5,
  ARRAY['tisane', 'matin', 'anti-inflammatoire'],
  '[{"name":"eau chaude (max 70°C)","qty":"300","unit":"mL"},{"name":"gingembre frais","qty":"3","unit":"tranches"},{"name":"citron (jus)","qty":"1","unit":"pièce"},{"name":"miel","qty":"1","unit":"c. à café"}]'::jsonb,
  '[{"step":1,"text":"Faire infuser le gingembre dans l''eau chaude 5 minutes."},{"step":2,"text":"Presser le citron et ajouter le jus."},{"step":3,"text":"Incorporer le miel et mélanger. Servir immédiatement."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '190d2379-8aae-4afc-89cb-ecf59bfd75e3'::uuid,
  'Eau détox concombre-menthe',
  'Eau aromatisée fraîche et légère à préparer la veille',
  'hydric'::day_type,
  NULL::meal_type,
  5,
  ARRAY['froid', 'infusé', 'détox'],
  '[{"name":"eau plate","qty":"1","unit":"L"},{"name":"concombre en fines rondelles","qty":"0.5","unit":"pièce"},{"name":"menthe fraîche","qty":"10","unit":"feuilles"},{"name":"citron vert en rondelles","qty":"1","unit":"pièce"}]'::jsonb,
  '[{"step":1,"text":"Placer toutes les tranches et les feuilles dans un pichet."},{"step":2,"text":"Couvrir d''eau et laisser infuser au réfrigérateur minimum 2h (idéalement une nuit)."},{"step":3,"text":"Servir frais tout au long de la journée."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  'ff1829a9-df47-461b-8001-59999e54d76a'::uuid,
  'Bouillon miso léger',
  'Bouillon japonais doux, riche en probiotiques naturels',
  'hydric'::day_type,
  NULL::meal_type,
  10,
  ARRAY['chaud', 'probiotiques', 'umami'],
  '[{"name":"eau chaude (max 70°C)","qty":"500","unit":"mL"},{"name":"pâte miso blanche","qty":"1","unit":"c. à soupe"},{"name":"tofu soyeux en petits dés","qty":"2","unit":"c. à soupe"},{"name":"algues wakamé séchées","qty":"1","unit":"c. à café"},{"name":"oignon vert émincé","qty":"1","unit":"pièce"}]'::jsonb,
  '[{"step":1,"text":"Diluer la pâte miso dans 2 c. à soupe d''eau tiède pour éviter les grumeaux."},{"step":2,"text":"Réhydrater les algues 5 min dans un peu d''eau."},{"step":3,"text":"Mélanger miso dilué, tofu, algues et eau chaude dans un bol. Parsemer d''oignon vert."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  'b41ce508-90e3-4a7b-88e6-0814c3412566'::uuid,
  'Jus vert pomme-épinard-gingembre',
  'Jus dilué vitaminé pour faire le plein d''énergie en douceur',
  'hydric'::day_type,
  NULL::meal_type,
  10,
  ARRAY['jus dilué', 'vitamines', 'énergie'],
  '[{"name":"pommes","qty":"2","unit":"pièces"},{"name":"épinards frais","qty":"1","unit":"poignée"},{"name":"gingembre frais","qty":"1","unit":"tranche"},{"name":"citron (jus)","qty":"0.5","unit":"pièce"},{"name":"eau pour diluer","qty":"200","unit":"mL"}]'::jsonb,
  '[{"step":1,"text":"Passer pommes, épinards et gingembre à l''extracteur ou au blender."},{"step":2,"text":"Filtrer si besoin avec une passoire fine."},{"step":3,"text":"Diluer avec l''eau et ajouter le jus de citron. Servir frais."}]'::jsonb,
  'essential'::plan_tier,
  true
),
(
  '6d7e5a52-ee41-40e7-824c-dd6149099e11'::uuid,
  'Soupe miso aux champignons',
  'Soupe légère et réconfortante pour les jours hydriques froids',
  'hydric'::day_type,
  NULL::meal_type,
  15,
  ARRAY['chaud', 'minéral', 'champignons'],
  '[{"name":"eau","qty":"600","unit":"mL"},{"name":"pâte miso rouge","qty":"1","unit":"c. à soupe"},{"name":"champignons shiitakés séchés","qty":"4","unit":"pièces"},{"name":"algues kombu séchées","qty":"1","unit":"c. à soupe"},{"name":"oignon vert","qty":"1","unit":"pièce"}]'::jsonb,
  '[{"step":1,"text":"Réhydrater les shiitakés et le kombu dans l''eau froide pendant 10 minutes."},{"step":2,"text":"Porter à frémissement sans faire bouillir. Retirer le kombu."},{"step":3,"text":"Hors du feu, diluer le miso dans le bouillon. Parsemer d''oignon vert émincé."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '766998f2-0725-45a2-8e99-eb2641d2a35b'::uuid,
  'Eau aromatisée fraise-basilic',
  'Eau infusée estivale sans sucre ajouté, fraîche et élégante',
  'hydric'::day_type,
  NULL::meal_type,
  5,
  ARRAY['froid', 'estival', 'sans sucre'],
  '[{"name":"eau plate ou gazeuse","qty":"1","unit":"L"},{"name":"fraises","qty":"8","unit":"pièces"},{"name":"basilic frais","qty":"5","unit":"feuilles"},{"name":"citron en rondelles","qty":"0.5","unit":"pièce"}]'::jsonb,
  '[{"step":1,"text":"Écraser légèrement les fraises à la fourchette pour libérer le jus."},{"step":2,"text":"Placer fraises, basilic et citron dans un pichet. Couvrir d''eau."},{"step":3,"text":"Infuser 1h minimum au frais avant de servir."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '1ab4818b-1b7b-42f5-8f45-1b77f5f6b9ab'::uuid,
  'Bouillon de poulet maison',
  'Bouillon réconfortant, dégraissé, idéal pour nourrir sans alourdir',
  'hydric'::day_type,
  NULL::meal_type,
  60,
  ARRAY['chaud', 'protéiné', 'réconfortant'],
  '[{"name":"eau froide","qty":"2","unit":"L"},{"name":"carcasse de poulet","qty":"500","unit":"g"},{"name":"carottes","qty":"2","unit":"pièces"},{"name":"oignon","qty":"1","unit":"pièce"},{"name":"thym","qty":"1","unit":"branche"},{"name":"feuille de laurier","qty":"1","unit":"pièce"},{"name":"sel, poivre","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Mettre tous les ingrédients dans une grande casserole avec l''eau froide."},{"step":2,"text":"Porter à ébullition, écumer puis réduire à feu doux."},{"step":3,"text":"Laisser mijoter 45 min. Filtrer soigneusement et dégraisser si nécessaire."},{"step":4,"text":"Servir chaud dans un bol. Conserve 3 jours au réfrigérateur."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  'da44bedc-32dd-40f8-80d1-9bbf80fc424c'::uuid,
  'Infusion hibiscus-grenade',
  'Tisane rouge et acidulée, riche en antioxydants, chaude ou froide',
  'hydric'::day_type,
  NULL::meal_type,
  8,
  ARRAY['tisane', 'antioxydants', 'chaud ou froid'],
  '[{"name":"eau chaude","qty":"400","unit":"mL"},{"name":"fleurs d''hibiscus séchées","qty":"2","unit":"c. à café"},{"name":"jus de grenade pur (sans sucre)","qty":"50","unit":"mL"},{"name":"miel (optionnel)","qty":"1","unit":"c. à café"}]'::jsonb,
  '[{"step":1,"text":"Infuser l''hibiscus dans l''eau chaude 7 minutes puis filtrer."},{"step":2,"text":"Ajouter le jus de grenade et le miel si souhaité."},{"step":3,"text":"Servir chaud ou sur des glaçons selon la saison."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '2b3cda1c-68ab-45cf-8969-11ca641472fb'::uuid,
  'Soupe froide concombre-yaourt',
  'Gazpacho blanc léger, frais et crémeux',
  'hydric'::day_type,
  NULL::meal_type,
  10,
  ARRAY['froid', 'léger', 'été'],
  '[{"name":"concombre","qty":"1","unit":"pièce"},{"name":"yaourt grec nature 0%","qty":"150","unit":"g"},{"name":"eau froide","qty":"150","unit":"mL"},{"name":"citron (jus)","qty":"1","unit":"pièce"},{"name":"menthe fraîche","qty":"5","unit":"feuilles"},{"name":"sel, poivre, cumin","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Peler et épépiner le concombre. Le couper en morceaux."},{"step":2,"text":"Mixer avec le yaourt, l''eau, le citron et la menthe."},{"step":3,"text":"Assaisonner. Réfrigérer 30 min avant de servir très frais."}]'::jsonb,
  'essential'::plan_tier,
  true
),
(
  'aff7d263-c25f-4ae0-86d7-81a4fac9b5e3'::uuid,
  'Overnight oats HYDRIC',
  'Petit-déjeuner préparé la veille, léger et rassasiant',
  'food'::day_type,
  'breakfast'::meal_type,
  10,
  ARRAY['sans cuisson', 'fibres', 'préparation veille'],
  '[{"name":"flocons d''avoine","qty":"50","unit":"g"},{"name":"lait végétal (avoine ou amande)","qty":"200","unit":"mL"},{"name":"graines de chia","qty":"1","unit":"c. à soupe"},{"name":"miel ou sirop d''érable","qty":"1","unit":"c. à café"},{"name":"fruits rouges frais ou surgelés","qty":"1","unit":"poignée"}]'::jsonb,
  '[{"step":1,"text":"Mélanger avoine, lait, chia et miel dans un bocal."},{"step":2,"text":"Fermer et réfrigérer toute la nuit."},{"step":3,"text":"Le matin, garnir de fruits rouges et servir directement dans le bocal."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '2d44c8c6-96ad-4734-8fbe-1588d50de1b1'::uuid,
  'Smoothie bowl énergie',
  'Bol vitaminé pour démarrer un jour alimentaire',
  'food'::day_type,
  'breakfast'::meal_type,
  8,
  ARRAY['fruits', 'rapide', 'vitamines'],
  '[{"name":"banane congelée","qty":"1","unit":"pièce"},{"name":"fruits rouges surgelés","qty":"100","unit":"g"},{"name":"yaourt grec nature","qty":"100","unit":"g"},{"name":"granola sans sucre","qty":"2","unit":"c. à soupe"},{"name":"graines (lin, tournesol)","qty":"1","unit":"c. à soupe"},{"name":"kiwi tranché","qty":"0.5","unit":"pièce"}]'::jsonb,
  '[{"step":1,"text":"Mixer banane, fruits rouges et yaourt jusqu''à texture épaisse et lisse."},{"step":2,"text":"Verser dans un bol. Garnir de granola, graines et kiwi."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  'f834543e-aa30-4dcb-89c0-b2bcc5a2131d'::uuid,
  'Toast avocat-œuf poché',
  'Le classique healthy pour un déjeuner rassasiant',
  'food'::day_type,
  'breakfast'::meal_type,
  12,
  ARRAY['protéiné', 'bon gras', 'rassasiant'],
  '[{"name":"pain complet ou au levain","qty":"2","unit":"tranches"},{"name":"avocat mûr","qty":"1","unit":"pièce"},{"name":"œufs","qty":"2","unit":"pièces"},{"name":"jus de citron","qty":"1","unit":"c. à soupe"},{"name":"flocons de piment, sel, poivre","qty":"0","unit":"pincée"},{"name":"roquette (optionnel)","qty":"1","unit":"poignée"}]'::jsonb,
  '[{"step":1,"text":"Toaster le pain. Écraser l''avocat avec le jus de citron, sel et poivre."},{"step":2,"text":"Pocher les œufs 3 min dans de l''eau frémissante vinaigrée."},{"step":3,"text":"Tartiner l''avocat sur les toasts, déposer les œufs pochés. Garnir de roquette et piment."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '4687ba1a-8938-4e0a-86bb-e455400bab34'::uuid,
  'Porridge banane-cannelle',
  'Bol chaud et doux pour un réveil tout en douceur',
  'food'::day_type,
  'breakfast'::meal_type,
  10,
  ARRAY['chaud', 'fibres', 'hiver'],
  '[{"name":"flocons d''avoine","qty":"60","unit":"g"},{"name":"lait végétal","qty":"300","unit":"mL"},{"name":"banane","qty":"1","unit":"pièce"},{"name":"cannelle","qty":"0.5","unit":"c. à café"},{"name":"beurre d''amande","qty":"1","unit":"c. à café"}]'::jsonb,
  '[{"step":1,"text":"Faire chauffer le lait végétal. Ajouter les flocons et la cannelle."},{"step":2,"text":"Cuire 5 min à feu doux en remuant. La texture doit être crémeuse."},{"step":3,"text":"Verser dans un bol. Trancher la banane dessus et ajouter le beurre d''amande."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '1b98892a-2542-4973-8fb7-3c4ef4bdac7f'::uuid,
  'Yaourt grec fruits secs et graines',
  'Petit-déjeuner express protéiné sans aucune cuisson',
  'food'::day_type,
  'breakfast'::meal_type,
  5,
  ARRAY['express', 'protéiné', 'sans cuisson'],
  '[{"name":"yaourt grec nature","qty":"200","unit":"g"},{"name":"miel","qty":"1","unit":"c. à soupe"},{"name":"noix","qty":"4","unit":"pièces"},{"name":"graines de courge","qty":"1","unit":"c. à soupe"},{"name":"dattes Medjool dénoyautées","qty":"4","unit":"pièces"}]'::jsonb,
  '[{"step":1,"text":"Verser le yaourt dans un bol."},{"step":2,"text":"Hacher grossièrement les noix et couper les dattes en morceaux."},{"step":3,"text":"Déposer sur le yaourt avec les graines. Arroser de miel."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '6e298611-a87c-4484-8d83-08077e31e182'::uuid,
  'Pancakes flocons d''avoine-myrtilles',
  'Pancakes légers sans farine blanche pour un brunch sain',
  'food'::day_type,
  'breakfast'::meal_type,
  20,
  ARRAY['brunch', 'sans gluten', 'gourmand'],
  '[{"name":"flocons d''avoine mixés en farine","qty":"80","unit":"g"},{"name":"œufs","qty":"2","unit":"pièces"},{"name":"lait végétal","qty":"100","unit":"mL"},{"name":"levure chimique","qty":"0.5","unit":"c. à café"},{"name":"myrtilles fraîches ou surgelées","qty":"80","unit":"g"},{"name":"huile de coco","qty":"1","unit":"c. à café"}]'::jsonb,
  '[{"step":1,"text":"Mixer les flocons en poudre. Mélanger avec œufs, lait et levure jusqu''à pâte lisse."},{"step":2,"text":"Chauffer une poêle huilée à feu moyen. Verser une louche de pâte."},{"step":3,"text":"Déposer quelques myrtilles sur chaque pancake. Cuire 2 min de chaque côté."}]'::jsonb,
  'essential'::plan_tier,
  true
),
(
  '3308464e-9b2a-44e9-883a-86a199d4b807'::uuid,
  'Bowl muesli-kéfir et poire',
  'Mélange croustillant avec kéfir pour la flore intestinale',
  'food'::day_type,
  'breakfast'::meal_type,
  5,
  ARRAY['probiotiques', 'croquant', 'express'],
  '[{"name":"kéfir de lait nature","qty":"150","unit":"mL"},{"name":"muesli sans sucre","qty":"40","unit":"g"},{"name":"poire","qty":"1","unit":"pièce"},{"name":"cannelle","qty":"1","unit":"c. à café"}]'::jsonb,
  '[{"step":1,"text":"Verser le kéfir dans un bol. Ajouter le muesli."},{"step":2,"text":"Trancher la poire finement et la déposer sur le muesli."},{"step":3,"text":"Saupoudrer de cannelle. Servir immédiatement pour garder le croquant."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '6baa64d3-aa18-4756-8838-b369be4f7fbd'::uuid,
  'Œufs brouillés aux herbes',
  'Petit-déjeuner savoureux et protéiné en moins de 10 minutes',
  'food'::day_type,
  'breakfast'::meal_type,
  10,
  ARRAY['protéiné', 'rapide', 'savoureux'],
  '[{"name":"œufs","qty":"3","unit":"pièces"},{"name":"pain de seigle","qty":"2","unit":"tranches"},{"name":"ciboulette ciselée","qty":"1","unit":"c. à soupe"},{"name":"beurre","qty":"1","unit":"c. à café"},{"name":"sel, poivre","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Toaster le pain. Battre les œufs avec une pincée de sel."},{"step":2,"text":"Faire fondre le beurre à feu doux. Ajouter les œufs et remuer continuellement à la spatule."},{"step":3,"text":"Retirer du feu avant qu''ils soient entièrement pris. Déposer sur le pain et parsemer de ciboulette."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '08bc1460-f1d2-4c30-8fc8-2f5336d73508'::uuid,
  'Chia pudding coco-mangue',
  'Pudding exotique préparé la veille, texture crémeuse',
  'food'::day_type,
  'breakfast'::meal_type,
  8,
  ARRAY['préparation veille', 'exotique', 'sans cuisson'],
  '[{"name":"graines de chia","qty":"3","unit":"c. à soupe"},{"name":"lait de coco léger","qty":"200","unit":"mL"},{"name":"mangue fraîche ou surgelée","qty":"100","unit":"g"},{"name":"vanille en poudre","qty":"1","unit":"c. à café"},{"name":"miel","qty":"1","unit":"c. à café"}]'::jsonb,
  '[{"step":1,"text":"Mélanger chia, lait de coco, vanille et miel dans un bocal. Bien remuer."},{"step":2,"text":"Laisser prendre au frigo une nuit (ou 4h minimum)."},{"step":3,"text":"Le matin, couper la mangue en dés et disposer sur le pudding."}]'::jsonb,
  'essential'::plan_tier,
  true
),
(
  '588f461a-b873-4500-8e6d-601fcc379eba'::uuid,
  'Toast ricotta-figues-noisettes',
  'Petit-déjeuner gourmand et équilibré pour les matins de week-end',
  'food'::day_type,
  'breakfast'::meal_type,
  8,
  ARRAY['gourmand', 'automne', 'rapide'],
  '[{"name":"pain complet","qty":"2","unit":"tranches"},{"name":"ricotta","qty":"80","unit":"g"},{"name":"figues fraîches","qty":"2","unit":"pièces"},{"name":"noisettes concassées","qty":"8","unit":"pièces"},{"name":"miel d''acacia","qty":"1","unit":"c. à café"}]'::jsonb,
  '[{"step":1,"text":"Toaster le pain."},{"step":2,"text":"Étaler la ricotta généreusement."},{"step":3,"text":"Couper les figues en quartiers et les disposer sur la ricotta. Parsemer de noisettes et arroser de miel."}]'::jsonb,
  'essential'::plan_tier,
  true
),
(
  '75a1c503-15b7-4cf3-8d73-8882fab5a3dc'::uuid,
  'Salade protéinée légère',
  'Salade complète pour un déjeuner équilibré',
  'food'::day_type,
  'lunch'::meal_type,
  15,
  ARRAY['protéine', 'équilibre', 'rapide'],
  '[{"name":"poulet grillé effiloché","qty":"100","unit":"g"},{"name":"mesclun","qty":"150","unit":"g"},{"name":"pois chiches égouttés","qty":"100","unit":"g"},{"name":"concombre","qty":"0.5","unit":"pièce"},{"name":"tomates cerises","qty":"10","unit":"pièces"},{"name":"huile d''olive","qty":"1","unit":"c. à soupe"},{"name":"jus de citron","qty":"1","unit":"c. à soupe"},{"name":"sel, poivre, cumin","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Disposer le mesclun dans un grand bol."},{"step":2,"text":"Ajouter poulet, pois chiches, concombre en dés et tomates cerises."},{"step":3,"text":"Assaisonner avec huile, citron, cumin, sel et poivre. Mélanger et servir."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '66440b45-c4c8-4c9a-8bf0-304cdc0bf709'::uuid,
  'Wrap poulet & crudités',
  'Déjeuner portable, équilibré et savoureux',
  'food'::day_type,
  'lunch'::meal_type,
  12,
  ARRAY['protéine', 'rapide', 'portable'],
  '[{"name":"tortillas complètes","qty":"2","unit":"pièces"},{"name":"filet de poulet cuit","qty":"150","unit":"g"},{"name":"houmous","qty":"2","unit":"c. à soupe"},{"name":"avocat","qty":"0.5","unit":"pièce"},{"name":"poivron rouge","qty":"0.5","unit":"pièce"},{"name":"concombre","qty":"0.25","unit":"pièce"},{"name":"roquette","qty":"1","unit":"poignée"}]'::jsonb,
  '[{"step":1,"text":"Étaler le houmous sur chaque tortilla."},{"step":2,"text":"Émincer le poulet, le poivron et le concombre."},{"step":3,"text":"Disposer tous les ingrédients au centre. Rouler et couper en deux."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '48e1a3ac-edc4-48a0-8afe-cb56be972cd7'::uuid,
  'Bowl quinoa légumes rôtis-feta',
  'Bowl coloré et rassasiant, idéal préparé en avance',
  'food'::day_type,
  'lunch'::meal_type,
  30,
  ARRAY['végétarien', 'meal prep', 'équilibre'],
  '[{"name":"quinoa","qty":"80","unit":"g"},{"name":"courgette","qty":"1","unit":"pièce"},{"name":"poivron rouge","qty":"1","unit":"pièce"},{"name":"pois chiches","qty":"100","unit":"g"},{"name":"feta émiettée","qty":"50","unit":"g"},{"name":"huile d''olive","qty":"2","unit":"c. à soupe"},{"name":"herbes de Provence","qty":"1","unit":"pincée"},{"name":"tahini","qty":"1","unit":"c. à soupe"},{"name":"citron (jus)","qty":"1","unit":"pièce"}]'::jsonb,
  '[{"step":1,"text":"Cuire le quinoa. Préchauffer le four à 200°C."},{"step":2,"text":"Couper les légumes en dés, mélanger avec huile et herbes, rôtir 20 min."},{"step":3,"text":"Préparer la sauce : tahini + jus de citron + 2 c. à soupe d''eau."},{"step":4,"text":"Assembler : quinoa, légumes rôtis, feta, pois chiches. Arroser de sauce tahini."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '9eaec9b2-2c7e-4c4a-8414-bc1b86a08a62'::uuid,
  'Soupe lentilles-cumin-citron',
  'Soupe épaisse, chaude et rassasiante pour les déjeuners froids',
  'food'::day_type,
  'lunch'::meal_type,
  35,
  ARRAY['chaud', 'vegan', 'hiver'],
  '[{"name":"lentilles corail","qty":"150","unit":"g"},{"name":"oignon","qty":"1","unit":"pièce"},{"name":"ail","qty":"2","unit":"gousses"},{"name":"carotte","qty":"1","unit":"pièce"},{"name":"bouillon de légumes","qty":"800","unit":"mL"},{"name":"cumin moulu","qty":"1","unit":"c. à café"},{"name":"citron (jus)","qty":"1","unit":"pièce"},{"name":"huile d''olive","qty":"1","unit":"c. à soupe"}]'::jsonb,
  '[{"step":1,"text":"Faire revenir oignon et ail hachés dans l''huile. Ajouter cumin et carotte."},{"step":2,"text":"Rincer les lentilles et les ajouter avec le bouillon. Cuire 25 min."},{"step":3,"text":"Mixer partiellement pour une texture mi-crémeuse. Ajouter le citron. Assaisonner."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '236bb495-ff97-4a79-8f3e-123cc204d28d'::uuid,
  'Tartines sardines et tomates',
  'Déjeuner méditerranéen rapide, riche en oméga-3',
  'food'::day_type,
  'lunch'::meal_type,
  10,
  ARRAY['oméga-3', 'méditerranéen', 'express'],
  '[{"name":"pain complet ou au levain","qty":"2","unit":"tranches"},{"name":"sardines à l''huile d''olive","qty":"1","unit":"boîte"},{"name":"tomates cerises","qty":"4","unit":"pièces"},{"name":"oignon rouge","qty":"0.25","unit":"pièce"},{"name":"basilic frais","qty":"5","unit":"feuilles"},{"name":"sel, poivre, filet de citron","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Toaster le pain. Écraser les sardines à la fourchette."},{"step":2,"text":"Étaler les sardines sur le pain. Couper les tomates et l''oignon en fines lamelles."},{"step":3,"text":"Disposer les légumes sur les sardines. Finir avec basilic et citron."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '5f04da00-4153-445c-8eb8-660ef72a0cd3'::uuid,
  'Pad thaï léger aux crevettes',
  'Version allégée du pad thaï avec nouilles de riz',
  'food'::day_type,
  'lunch'::meal_type,
  20,
  ARRAY['asiatique', 'protéiné', 'savoureux'],
  '[{"name":"nouilles de riz","qty":"100","unit":"g"},{"name":"crevettes décortiquées","qty":"150","unit":"g"},{"name":"œufs","qty":"2","unit":"pièces"},{"name":"germes de soja","qty":"1","unit":"poignée"},{"name":"oignons verts","qty":"2","unit":"pièces"},{"name":"sauce tamari","qty":"2","unit":"c. à soupe"},{"name":"huile de sésame","qty":"1","unit":"c. à café"},{"name":"citron vert","qty":"1","unit":"pièce"},{"name":"cacahuètes concassées","qty":"1","unit":"c. à soupe"}]'::jsonb,
  '[{"step":1,"text":"Cuire les nouilles al dente selon le paquet. Égoutter."},{"step":2,"text":"Sauter les crevettes à la poêle. Pousser sur le côté et brouiller les œufs."},{"step":3,"text":"Ajouter nouilles, tamari, germes de soja. Mélanger 2 min."},{"step":4,"text":"Servir avec oignons verts, cacahuètes et citron vert."}]'::jsonb,
  'essential'::plan_tier,
  true
),
(
  '4d64d255-50fc-4c33-8f35-29556699ea66'::uuid,
  'Salade de pois chiches épicée',
  'Salade vegan consistante avec une touche orientale',
  'food'::day_type,
  'lunch'::meal_type,
  12,
  ARRAY['vegan', 'épicé', 'fibres'],
  '[{"name":"pois chiches cuits","qty":"400","unit":"g"},{"name":"tomates","qty":"2","unit":"pièces"},{"name":"oignon rouge","qty":"0.5","unit":"pièce"},{"name":"persil frais","qty":"1","unit":"bouquet"},{"name":"huile d''olive","qty":"2","unit":"c. à soupe"},{"name":"cumin","qty":"1","unit":"c. à café"},{"name":"paprika fumé","qty":"0.5","unit":"c. à café"},{"name":"citron (jus)","qty":"1","unit":"pièce"}]'::jsonb,
  '[{"step":1,"text":"Égoutter et rincer les pois chiches. Couper tomates et oignon en dés."},{"step":2,"text":"Mélanger épices, huile et citron pour la vinaigrette."},{"step":3,"text":"Mélanger tout, parsemer de persil. Peut se déguster tiède ou froid."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '3420590d-9077-4459-8a92-e037f7bf9348'::uuid,
  'Bowl saumon teriyaki-riz brun',
  'Bowl japonais équilibré avec saumon glacé maison',
  'food'::day_type,
  'lunch'::meal_type,
  25,
  ARRAY['japonais', 'oméga-3', 'meal prep'],
  '[{"name":"filet de saumon","qty":"150","unit":"g"},{"name":"riz brun","qty":"80","unit":"g"},{"name":"sauce tamari","qty":"2","unit":"c. à soupe"},{"name":"miel","qty":"1","unit":"c. à soupe"},{"name":"gingembre frais râpé","qty":"1","unit":"c. à café"},{"name":"concombre","qty":"0.5","unit":"pièce"},{"name":"carotte râpée","qty":"1","unit":"pièce"},{"name":"graines de sésame","qty":"1","unit":"c. à café"}]'::jsonb,
  '[{"step":1,"text":"Cuire le riz brun. Mélanger tamari, miel et gingembre pour la sauce teriyaki."},{"step":2,"text":"Faire mariner le saumon 10 min puis le cuire à la poêle 4 min de chaque côté en l''arrosant de sauce."},{"step":3,"text":"Assembler le bowl : riz, saumon, légumes crus. Parsemer de sésame."}]'::jsonb,
  'essential'::plan_tier,
  true
),
(
  '6754f063-2d03-4da7-859c-2f89b1c9ef3e'::uuid,
  'Frittata légumes du soleil',
  'Frittata aérienne aux légumes d''été, chaude ou froide',
  'food'::day_type,
  'lunch'::meal_type,
  25,
  ARRAY['végétarien', 'protéiné', 'été'],
  '[{"name":"œufs","qty":"4","unit":"pièces"},{"name":"courgette","qty":"1","unit":"pièce"},{"name":"poivron rouge","qty":"0.5","unit":"pièce"},{"name":"tomates cerises","qty":"100","unit":"g"},{"name":"feta émiettée","qty":"30","unit":"g"},{"name":"basilic","qty":"5","unit":"feuilles"},{"name":"huile d''olive","qty":"1","unit":"c. à soupe"},{"name":"sel, poivre","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Faire revenir les légumes coupés en dés dans l''huile 5 min. Préchauffer le four à 180°C."},{"step":2,"text":"Battre les œufs avec sel et poivre. Verser sur les légumes dans un plat allant au four."},{"step":3,"text":"Parsemer de feta. Enfourner 15 min. Servir avec basilic frais."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  'ddb69a95-009c-47f9-80c3-d8e8c0e6d802'::uuid,
  'Soupe patate douce-coco',
  'Velouté doux et onctueux, vegan et réconfortant',
  'food'::day_type,
  'lunch'::meal_type,
  30,
  ARRAY['vegan', 'velouté', 'hiver'],
  '[{"name":"patate douce","qty":"400","unit":"g"},{"name":"lait de coco","qty":"200","unit":"mL"},{"name":"bouillon de légumes","qty":"400","unit":"mL"},{"name":"oignon","qty":"1","unit":"pièce"},{"name":"ail","qty":"2","unit":"gousses"},{"name":"curry doux","qty":"1","unit":"c. à café"},{"name":"huile d''olive","qty":"1","unit":"c. à soupe"}]'::jsonb,
  '[{"step":1,"text":"Faire revenir oignon et ail dans l''huile. Ajouter le curry 1 minute."},{"step":2,"text":"Ajouter patate douce pelée en dés et le bouillon. Cuire 20 min."},{"step":3,"text":"Mixer. Incorporer le lait de coco. Rectifier l''assaisonnement."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '3ad65953-f31b-4231-8ff6-0b5d17d8e16a'::uuid,
  'Bowl quinoa & légumes rôtis',
  'Repas complet et végétarien pour finir la journée légèrement',
  'food'::day_type,
  'dinner'::meal_type,
  30,
  ARRAY['végétarien', 'quinoa', 'complet'],
  '[{"name":"quinoa","qty":"80","unit":"g"},{"name":"courgette","qty":"1","unit":"pièce"},{"name":"aubergine","qty":"1","unit":"pièce"},{"name":"tomates cerises","qty":"100","unit":"g"},{"name":"huile d''olive","qty":"2","unit":"c. à soupe"},{"name":"herbes de Provence","qty":"1","unit":"pincée"},{"name":"feta ou parmesan","qty":"30","unit":"g"}]'::jsonb,
  '[{"step":1,"text":"Cuire le quinoa. Préchauffer le four à 200°C."},{"step":2,"text":"Couper les légumes en dés, huiler, assaisonner, rôtir 20 min."},{"step":3,"text":"Assembler : quinoa, légumes rôtis, fromage émietté."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '8f24d6b1-43e9-4b32-89fa-024f130f3677'::uuid,
  'Poisson vapeur & légumes verts',
  'Dîner ultra-léger, idéal en fin de journée alimentaire',
  'food'::day_type,
  'dinner'::meal_type,
  20,
  ARRAY['poisson', 'léger', 'vapeur'],
  '[{"name":"filet de cabillaud ou dorade","qty":"180","unit":"g"},{"name":"haricots verts","qty":"150","unit":"g"},{"name":"brocoli","qty":"150","unit":"g"},{"name":"citron","qty":"1","unit":"pièce"},{"name":"huile d''olive","qty":"1","unit":"c. à soupe"},{"name":"sel, poivre, aneth","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Cuire les légumes et le poisson à la vapeur 12-15 min."},{"step":2,"text":"Assaisonner le poisson avec citron, aneth, sel et poivre."},{"step":3,"text":"Servir avec un filet d''huile d''olive sur les légumes."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  'd8322700-362d-4b9c-812d-4a230074ef15'::uuid,
  'Poulet rôti citron-herbes & patates douces',
  'Plat familial simple et équilibré',
  'food'::day_type,
  'dinner'::meal_type,
  45,
  ARRAY['protéiné', 'four', 'familial'],
  '[{"name":"cuisses de poulet","qty":"2","unit":"pièces"},{"name":"patate douce","qty":"300","unit":"g"},{"name":"citron","qty":"1","unit":"pièce"},{"name":"ail","qty":"3","unit":"gousses"},{"name":"romarin","qty":"1","unit":"branche"},{"name":"huile d''olive","qty":"2","unit":"c. à soupe"},{"name":"sel, poivre","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Préchauffer le four à 200°C. Couper les patates douces en quartiers."},{"step":2,"text":"Déposer cuisses et patates dans un plat. Arroser d''huile, citron, ail et romarin."},{"step":3,"text":"Enfourner 40 min en arrosant à mi-cuisson."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '0761185b-52bc-4444-8d3e-501f5743e83f'::uuid,
  'Curry de lentilles corail-épinards',
  'Curry vegan doux et crémeux prêt en 25 minutes',
  'food'::day_type,
  'dinner'::meal_type,
  25,
  ARRAY['vegan', 'curry', 'fibres'],
  '[{"name":"lentilles corail","qty":"150","unit":"g"},{"name":"lait de coco","qty":"200","unit":"mL"},{"name":"bouillon de légumes","qty":"300","unit":"mL"},{"name":"épinards frais","qty":"100","unit":"g"},{"name":"oignon","qty":"1","unit":"pièce"},{"name":"curry doux","qty":"2","unit":"c. à café"},{"name":"curcuma","qty":"1","unit":"c. à café"},{"name":"huile de coco","qty":"1","unit":"c. à soupe"}]'::jsonb,
  '[{"step":1,"text":"Faire revenir l''oignon dans l''huile. Ajouter épices 1 min."},{"step":2,"text":"Ajouter lentilles rincées, bouillon et lait de coco. Cuire 20 min."},{"step":3,"text":"Incorporer les épinards 2 min avant la fin. Servir avec riz basmati si souhaité."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '68837b6e-6479-4eae-8ed4-c12494cec25f'::uuid,
  'Soupe ramen maison allégée',
  'Ramen doux et réconfortant sans la lourdeur du restaurant',
  'food'::day_type,
  'dinner'::meal_type,
  30,
  ARRAY['japonais', 'chaud', 'réconfortant'],
  '[{"name":"nouilles ramen de blé ou de riz","qty":"100","unit":"g"},{"name":"bouillon de poulet maison","qty":"800","unit":"mL"},{"name":"œufs mollets","qty":"2","unit":"pièces"},{"name":"champignons shiitakés","qty":"100","unit":"g"},{"name":"oignons verts","qty":"2","unit":"pièces"},{"name":"sauce tamari","qty":"1","unit":"c. à soupe"},{"name":"gingembre frais râpé","qty":"1","unit":"c. à café"}]'::jsonb,
  '[{"step":1,"text":"Cuire les œufs 7 min pour des œufs mollets. Les écaler et couper en 2."},{"step":2,"text":"Faire chauffer le bouillon avec tamari et gingembre. Ajouter les champignons."},{"step":3,"text":"Cuire les nouilles à part. Assembler : nouilles, bouillon chaud, œuf, oignon vert."}]'::jsonb,
  'essential'::plan_tier,
  true
),
(
  '8a402d16-a95e-4418-8b7c-621881a791be'::uuid,
  'Dos de cabillaud en croûte d''herbes',
  'Filet de poisson élégant avec croûte croustillante de persil et noisettes',
  'food'::day_type,
  'dinner'::meal_type,
  25,
  ARRAY['poisson', 'élégant', 'four'],
  '[{"name":"dos de cabillaud (170g chacun)","qty":"2","unit":"pièces"},{"name":"persil haché","qty":"2","unit":"c. à soupe"},{"name":"noisettes moulues","qty":"2","unit":"c. à soupe"},{"name":"chapelure complète","qty":"1","unit":"c. à soupe"},{"name":"huile d''olive","qty":"1","unit":"c. à soupe"},{"name":"citron","qty":"1","unit":"pièce"},{"name":"sel, poivre","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Préchauffer le four à 190°C. Mélanger persil, noisettes, chapelure et huile."},{"step":2,"text":"Poser les cabillauds dans un plat huilé. Répartir la croûte d''herbes dessus."},{"step":3,"text":"Enfourner 15-18 min. Servir avec quartiers de citron et légumes vapeur."}]'::jsonb,
  'essential'::plan_tier,
  true
),
(
  '4d844f53-4db9-4de9-82a2-fa2c6f7e7a4a'::uuid,
  'Galettes de pois chiches-curcuma',
  'Galettes vegan croustillantes, servies avec yaourt à la menthe',
  'food'::day_type,
  'dinner'::meal_type,
  20,
  ARRAY['vegan', 'croustillant', 'protéiné végétal'],
  '[{"name":"pois chiches cuits","qty":"400","unit":"g"},{"name":"oignon","qty":"1","unit":"pièce"},{"name":"ail","qty":"2","unit":"gousses"},{"name":"curcuma","qty":"1","unit":"c. à café"},{"name":"cumin","qty":"1","unit":"c. à café"},{"name":"farine de pois chiche","qty":"2","unit":"c. à soupe"},{"name":"yaourt grec + menthe pour servir","qty":"100","unit":"g"},{"name":"huile d''olive","qty":"1","unit":"c. à soupe"}]'::jsonb,
  '[{"step":1,"text":"Mixer grossièrement les pois chiches avec oignon, ail et épices. Ne pas trop mixer — garder de la texture."},{"step":2,"text":"Ajouter la farine et former des galettes avec les mains."},{"step":3,"text":"Cuire à la poêle huilée 4 min de chaque côté. Servir avec yaourt-menthe."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '77181308-aac6-4633-884d-697a2f3c7a9f'::uuid,
  'Gratin courge butternut-chèvre',
  'Gratin doux et fondant, végétarien et réconfortant',
  'food'::day_type,
  'dinner'::meal_type,
  45,
  ARRAY['végétarien', 'gratin', 'automne'],
  '[{"name":"courge butternut","qty":"600","unit":"g"},{"name":"chèvre frais","qty":"80","unit":"g"},{"name":"crème de soja légère","qty":"150","unit":"mL"},{"name":"ail","qty":"2","unit":"gousses"},{"name":"thym frais","qty":"1","unit":"branche"},{"name":"noix de muscade, sel, poivre","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Préchauffer le four à 180°C. Éplucher et trancher finement la courge."},{"step":2,"text":"Disposer en couches dans un plat. Émietter le chèvre entre les couches."},{"step":3,"text":"Mélanger crème, ail, thym et muscade. Verser sur la courge. Enfourner 40 min."}]'::jsonb,
  'essential'::plan_tier,
  true
),
(
  'ec70ce58-d416-4691-8e7c-b8237723f2e4'::uuid,
  'Crevettes sautées ail-courgettes',
  'Plat rapide, léger et parfumé pour les soirs de semaine',
  'food'::day_type,
  'dinner'::meal_type,
  15,
  ARRAY['rapide', 'léger', 'fruits de mer'],
  '[{"name":"crevettes décortiquées","qty":"200","unit":"g"},{"name":"courgettes","qty":"2","unit":"pièces"},{"name":"ail","qty":"3","unit":"gousses"},{"name":"citron","qty":"1","unit":"pièce"},{"name":"huile d''olive","qty":"1","unit":"c. à soupe"},{"name":"persil plat","qty":"1","unit":"bouquet"},{"name":"sel, poivre, piment doux","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Couper les courgettes en fines rondelles. Émincer l''ail."},{"step":2,"text":"Faire sauter l''ail dans l''huile 1 min. Ajouter crevettes et courgettes. Cuire 5-6 min."},{"step":3,"text":"Finir avec citron, persil et piment. Servir seul ou avec du riz basmati."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  'c60de396-0e0b-4b13-80be-8a4a9a865c7a'::uuid,
  'Tartare de saumon avocat-sésame',
  'Dîner frais et élégant sans cuisson, riche en bons gras',
  'food'::day_type,
  'dinner'::meal_type,
  15,
  ARRAY['cru', 'oméga-3', 'sans cuisson'],
  '[{"name":"saumon frais (qualité sashimi)","qty":"200","unit":"g"},{"name":"avocat","qty":"1","unit":"pièce"},{"name":"sauce tamari","qty":"1","unit":"c. à soupe"},{"name":"huile de sésame","qty":"1","unit":"c. à café"},{"name":"gingembre frais râpé","qty":"1","unit":"c. à café"},{"name":"citron vert","qty":"1","unit":"pièce"},{"name":"graines de sésame","qty":"1","unit":"c. à café"},{"name":"oignons verts","qty":"2","unit":"pièces"}]'::jsonb,
  '[{"step":1,"text":"Couper le saumon en petits dés réguliers. Couper l''avocat en dés similaires."},{"step":2,"text":"Mélanger tamari, huile de sésame, gingembre et jus de citron vert."},{"step":3,"text":"Mélanger saumon et avocat avec la sauce. Dresser dans des cercles. Parsemer de sésame et oignon vert."}]'::jsonb,
  'essential'::plan_tier,
  true
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  day_type = EXCLUDED.day_type,
  meal_type = EXCLUDED.meal_type,
  duration_min = EXCLUDED.duration_min,
  tags = EXCLUDED.tags,
  ingredients = EXCLUDED.ingredients,
  steps = EXCLUDED.steps,
  plan_required = EXCLUDED.plan_required,
  published = EXCLUDED.published;
