-- Catalogue HYDRIC — 40 recettes
-- Source: data/hydric_recipes.json
-- Généré: 2026-06-12

DELETE FROM public.recipes;

INSERT INTO public.recipes (
  id, title, description, day_type, meal_type, duration_min,
  tags, ingredients, steps, plan_required, published
)
VALUES
(
  '9b8a7ad2-1b8c-46c0-8215-ee9f7e53b1f0'::uuid,
  'Bouillon dashi maison',
  'Bouillon japonais umami ultra-léger à base d''algues et de flocons de bonite',
  'hydric'::day_type,
  NULL::meal_type,
  15,
  ARRAY['japonais', 'umami', 'léger'],
  '[{"name":"eau froide","qty":"1","unit":"L"},{"name":"algues kombu séchées","qty":"15","unit":"g"},{"name":"flocons de bonite séchée (katsuobushi)","qty":"20","unit":"g"},{"name":"sauce tamari légère","qty":"1","unit":"c. à soupe"},{"name":"sel","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Faire tremper le kombu dans l''eau froide 30 min."},{"step":2,"text":"Porter à frémissement sans faire bouillir. Retirer le kombu."},{"step":3,"text":"Ajouter les flocons de bonite, éteindre le feu, infuser 5 min puis filtrer."},{"step":4,"text":"Assaisonner avec la sauce tamari. Servir chaud dans un bol."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '4a10b05c-a9fb-421d-80b2-10249d7346cb'::uuid,
  'Eau infusée pomme-cannelle-étoile de badiane',
  'Eau aromatisée chaude aux épices douces, idéale en hiver',
  'hydric'::day_type,
  NULL::meal_type,
  12,
  ARRAY['épicé', 'hivernal', 'chaud'],
  '[{"name":"eau","qty":"1","unit":"L"},{"name":"pomme en fines tranches","qty":"1","unit":"pièce"},{"name":"cannelle","qty":"1","unit":"bâton"},{"name":"étoiles de badiane","qty":"2","unit":"pièces"},{"name":"clous de girofle","qty":"3","unit":"pièces"},{"name":"miel (optionnel)","qty":"1","unit":"c. à café"}]'::jsonb,
  '[{"step":1,"text":"Mettre tous les ingrédients dans une casserole avec l''eau."},{"step":2,"text":"Porter à frémissement et laisser infuser 10 min à feu doux."},{"step":3,"text":"Filtrer et servir chaud. Ajouter le miel si souhaité."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  'a8f835e1-08b0-4317-803c-1a30e38d632f'::uuid,
  'Bouillon betterave-gingembre',
  'Bouillon rouge vif, doux et légèrement sucré, riche en antioxydants',
  'hydric'::day_type,
  NULL::meal_type,
  35,
  ARRAY['antioxydants', 'coloré', 'détox'],
  '[{"name":"betteraves crues","qty":"2","unit":"pièces"},{"name":"eau","qty":"1.5","unit":"L"},{"name":"gingembre frais","qty":"2","unit":"tranches"},{"name":"citron (jus)","qty":"1","unit":"pièce"},{"name":"oignon","qty":"1","unit":"pièce"},{"name":"sel, poivre","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Éplucher et couper les betteraves en cubes. Émincer l''oignon."},{"step":2,"text":"Mettre betteraves, oignon et gingembre dans l''eau froide. Porter à ébullition."},{"step":3,"text":"Cuire 30 min à feu doux. Filtrer, ajouter le citron et assaisonner. Servir chaud ou tiède."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  'da5e7e2d-53c5-4df6-8ec1-6ed442f7eed3'::uuid,
  'Tisane ortie-citron-miel',
  'Infusion reminéralisante à base d''ortie, légèrement herbacée',
  'hydric'::day_type,
  NULL::meal_type,
  8,
  ARRAY['reminéralisant', 'plantes', 'détox'],
  '[{"name":"eau chaude","qty":"400","unit":"mL"},{"name":"feuilles d''ortie séchées","qty":"2","unit":"c. à café"},{"name":"citron (jus)","qty":"0.5","unit":"pièce"},{"name":"miel","qty":"1","unit":"c. à café"}]'::jsonb,
  '[{"step":1,"text":"Faire bouillir l''eau. Verser sur les feuilles d''ortie dans une tasse ou théière."},{"step":2,"text":"Infuser 7 min puis filtrer."},{"step":3,"text":"Ajouter le jus de citron et le miel. Servir chaud."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '4abfcd4f-65e0-4143-85f1-450c9ef4a062'::uuid,
  'Agua fresca pastèque-menthe',
  'Boisson mexicaine rafraîchissante, légère et sans sucre ajouté',
  'hydric'::day_type,
  NULL::meal_type,
  8,
  ARRAY['froid', 'estival', 'sans sucre'],
  '[{"name":"pastèque épépinée","qty":"400","unit":"g"},{"name":"eau froide","qty":"300","unit":"mL"},{"name":"menthe fraîche","qty":"8","unit":"feuilles"},{"name":"citron vert (jus)","qty":"0.5","unit":"pièce"},{"name":"sel (une pincée pour relever)","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Mixer la pastèque avec l''eau jusqu''à consistance lisse."},{"step":2,"text":"Filtrer avec une passoire fine pour un résultat plus léger."},{"step":3,"text":"Ajouter citron vert, menthe froissée et une pincée de sel. Servir sur glace."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  'c9363333-21e7-4616-89fe-17b6a09cf920'::uuid,
  'Bouillon champignons-thym-laurier',
  'Bouillon forestier profond et aromatique, sans aucune graisse',
  'hydric'::day_type,
  NULL::meal_type,
  40,
  ARRAY['forestier', 'chaud', 'aromatique'],
  '[{"name":"champignons de Paris","qty":"200","unit":"g"},{"name":"champignons séchés (shiitaké ou cèpes)","qty":"20","unit":"g"},{"name":"eau","qty":"1.5","unit":"L"},{"name":"thym","qty":"2","unit":"branches"},{"name":"feuilles de laurier","qty":"2","unit":"pièces"},{"name":"ail","qty":"2","unit":"gousses"},{"name":"sel, poivre","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Réhydrater les champignons séchés 15 min dans un peu d''eau tiède."},{"step":2,"text":"Faire revenir à sec les champignons frais dans une casserole 5 min."},{"step":3,"text":"Ajouter l''eau, les champignons réhydratés, thym, laurier et ail. Mijoter 30 min."},{"step":4,"text":"Filtrer, assaisonner et servir chaud."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '27be6c27-7a31-45c1-8db0-74e67f446127'::uuid,
  'Kéfir d''eau citron-gingembre',
  'Boisson probiotique légèrement pétillante, douce et digestive',
  'hydric'::day_type,
  NULL::meal_type,
  5,
  ARRAY['probiotiques', 'pétillant', 'digestif'],
  '[{"name":"kéfir d''eau nature (prêt à consommer)","qty":"250","unit":"mL"},{"name":"citron (jus)","qty":"0.5","unit":"pièce"},{"name":"gingembre frais","qty":"1","unit":"tranche"},{"name":"miel (optionnel)","qty":"1","unit":"c. à café"}]'::jsonb,
  '[{"step":1,"text":"Verser le kéfir d''eau dans un verre."},{"step":2,"text":"Presser le citron, râper un peu de gingembre, ajouter le miel si souhaité."},{"step":3,"text":"Mélanger doucement pour ne pas perdre le pétillant. Servir frais."}]'::jsonb,
  'essential'::plan_tier,
  true
),
(
  '7b6e16a4-3fd4-442a-8458-6540fcffc377'::uuid,
  'Bouillon asiatique lemongrass-coriandre',
  'Bouillon léger et parfumé aux saveurs thaïes, sans matières grasses',
  'hydric'::day_type,
  NULL::meal_type,
  20,
  ARRAY['thaï', 'citronné', 'aromatique'],
  '[{"name":"eau","qty":"1","unit":"L"},{"name":"lemongrass (citronnelle) fendue","qty":"2","unit":"tiges"},{"name":"kaffir lime (combava)","qty":"3","unit":"feuilles"},{"name":"galanga ou gingembre","qty":"2","unit":"tranches"},{"name":"piment oiseau (optionnel)","qty":"1","unit":"pièce"},{"name":"sauce poisson (nuoc-mâm)","qty":"1","unit":"c. à soupe"},{"name":"coriandre fraîche","qty":"1","unit":"bouquet"}]'::jsonb,
  '[{"step":1,"text":"Porter l''eau à ébullition. Ajouter lemongrass, kaffir, galanga et piment."},{"step":2,"text":"Mijoter 15 min à feu doux. Assaisonner avec le nuoc-mâm."},{"step":3,"text":"Filtrer et servir chaud, parsemé de feuilles de coriandre fraîche."}]'::jsonb,
  'essential'::plan_tier,
  true
),
(
  '13545c6e-b536-486e-8f13-bc7c3d0672ec'::uuid,
  'Eau infusée ananas-menthe-citron vert',
  'Eau détox tropicale, légère et ultra-rafraîchissante',
  'hydric'::day_type,
  NULL::meal_type,
  5,
  ARRAY['tropical', 'froid', 'sans sucre'],
  '[{"name":"ananas frais","qty":"3","unit":"tranches"},{"name":"menthe fraîche","qty":"8","unit":"feuilles"},{"name":"citron vert en rondelles","qty":"1","unit":"pièce"},{"name":"eau plate ou gazeuse","qty":"1","unit":"L"}]'::jsonb,
  '[{"step":1,"text":"Couper l''ananas en petits morceaux et les écraser légèrement."},{"step":2,"text":"Placer ananas, menthe et citron vert dans un pichet. Couvrir d''eau."},{"step":3,"text":"Infuser 2h minimum au réfrigérateur. Servir sur glace."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  'bc3e778a-a569-4f5f-81a8-1c56ac86ae95'::uuid,
  'Bouillon miso-tomate-basilic',
  'Bouillon fusion italo-japonais, doux et umami, surprenant et réconfortant',
  'hydric'::day_type,
  NULL::meal_type,
  15,
  ARRAY['fusion', 'umami', 'tomate'],
  '[{"name":"eau chaude","qty":"600","unit":"mL"},{"name":"pâte miso blanche","qty":"1","unit":"c. à soupe"},{"name":"concentré de tomate","qty":"2","unit":"c. à soupe"},{"name":"basilic frais","qty":"5","unit":"feuilles"},{"name":"piment doux","qty":"1","unit":"pincée"},{"name":"sel si nécessaire","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Diluer le miso et le concentré de tomate dans l''eau chaude (max 70°C) en fouettant."},{"step":2,"text":"Goûter et ajuster l''assaisonnement."},{"step":3,"text":"Servir dans un bol avec les feuilles de basilic déchirées et une pincée de piment."}]'::jsonb,
  'essential'::plan_tier,
  true
),
(
  '77abd66c-0965-4ad6-8093-8dd999eea11c'::uuid,
  'Granola maison miel-noix de coco',
  'Granola croustillant sans sucre raffiné à préparer le week-end',
  'food'::day_type,
  'breakfast'::meal_type,
  30,
  ARRAY['meal prep', 'croustillant', 'sans sucre raffiné'],
  '[{"name":"flocons d''avoine","qty":"200","unit":"g"},{"name":"noix de coco râpée","qty":"50","unit":"g"},{"name":"amandes effilées","qty":"50","unit":"g"},{"name":"miel","qty":"3","unit":"c. à soupe"},{"name":"huile de coco","qty":"2","unit":"c. à soupe"},{"name":"cannelle","qty":"1","unit":"c. à café"},{"name":"sel","qty":"1","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Préchauffer le four à 160°C. Mélanger tous les ingrédients secs."},{"step":2,"text":"Faire fondre l''huile de coco avec le miel. Verser sur le mélange sec et bien mélanger."},{"step":3,"text":"Étaler sur une plaque. Cuire 20-25 min en remuant à mi-cuisson. Laisser refroidir avant de stocker."}]'::jsonb,
  'essential'::plan_tier,
  true
),
(
  'fc685ba0-440c-49a2-833e-701bd9dbc91e'::uuid,
  'Tartine beurre d''amande-banane-graines',
  'Petit-déjeuner express riche en bons gras et en potassium',
  'food'::day_type,
  'breakfast'::meal_type,
  5,
  ARRAY['express', 'énergie', 'bons gras'],
  '[{"name":"pain complet ou épeautre","qty":"2","unit":"tranches"},{"name":"beurre d''amande","qty":"2","unit":"c. à soupe"},{"name":"banane","qty":"1","unit":"pièce"},{"name":"graines de sésame","qty":"1","unit":"c. à café"},{"name":"cannelle","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Toaster le pain."},{"step":2,"text":"Étaler le beurre d''amande généreusement."},{"step":3,"text":"Trancher la banane et disposer sur le pain. Saupoudrer de sésame et de cannelle."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '082460eb-e249-4498-8827-47d1124f9ff0'::uuid,
  'Omelette aux herbes fraîches',
  'Omelette légère et parfumée, idéale pour un petit-déjeuner protéiné sans effort',
  'food'::day_type,
  'breakfast'::meal_type,
  8,
  ARRAY['protéiné', 'rapide', 'herbes'],
  '[{"name":"œufs","qty":"3","unit":"pièces"},{"name":"ciboulette ciselée","qty":"1","unit":"c. à soupe"},{"name":"persil haché","qty":"1","unit":"c. à soupe"},{"name":"beurre","qty":"1","unit":"c. à café"},{"name":"feta émiettée (optionnel)","qty":"30","unit":"g"},{"name":"sel, poivre","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Battre les œufs avec les herbes, sel et poivre."},{"step":2,"text":"Faire fondre le beurre à feu moyen dans une poêle. Verser les œufs."},{"step":3,"text":"Laisser prendre les bords, rabattre et glisser dans l''assiette. Parsemer de feta si souhaité."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '2c879b27-6798-42a9-8c7a-e781e309ca2b'::uuid,
  'Bowl açaï maison',
  'Bowl violet intense, riche en antioxydants, façon brunch sain',
  'food'::day_type,
  'breakfast'::meal_type,
  10,
  ARRAY['antioxydants', 'brunch', 'coloré'],
  '[{"name":"pulpe d''açaï surgelée","qty":"100","unit":"g"},{"name":"banane congelée","qty":"1","unit":"pièce"},{"name":"lait de coco ou végétal","qty":"100","unit":"mL"},{"name":"granola","qty":"2","unit":"c. à soupe"},{"name":"noix de coco râpée","qty":"1","unit":"c. à soupe"},{"name":"myrtilles","qty":"1","unit":"poignée"},{"name":"miel","qty":"1","unit":"c. à café"}]'::jsonb,
  '[{"step":1,"text":"Mixer açaï, banane congelée et lait végétal jusqu''à texture crémeuse et épaisse."},{"step":2,"text":"Verser dans un bol. Garnir de granola, noix de coco, myrtilles et miel."}]'::jsonb,
  'essential'::plan_tier,
  true
),
(
  '8a62ab24-5300-4269-8779-29c4519869ed'::uuid,
  'Muffins avoine-myrtilles sans beurre',
  'Muffins moelleux à préparer en batch pour la semaine',
  'food'::day_type,
  'breakfast'::meal_type,
  30,
  ARRAY['meal prep', 'sans beurre', 'batch cooking'],
  '[{"name":"flocons d''avoine","qty":"150","unit":"g"},{"name":"œufs","qty":"2","unit":"pièces"},{"name":"lait végétal","qty":"150","unit":"mL"},{"name":"miel","qty":"2","unit":"c. à soupe"},{"name":"levure chimique","qty":"1","unit":"c. à café"},{"name":"myrtilles","qty":"100","unit":"g"},{"name":"banane écrasée","qty":"1","unit":"pièce"}]'::jsonb,
  '[{"step":1,"text":"Préchauffer le four à 180°C. Mélanger avoine, levure et banane écrasée."},{"step":2,"text":"Ajouter œufs, lait et miel. Incorporer délicatement les myrtilles."},{"step":3,"text":"Verser dans des moules à muffins. Cuire 20-25 min. Laisser refroidir avant de démouler."}]'::jsonb,
  'essential'::plan_tier,
  true
),
(
  '2ed7be43-2819-4029-837e-983d60407212'::uuid,
  'Toast sardines-avocat-câpres',
  'Petit-déjeuner salé méditerranéen riche en oméga-3',
  'food'::day_type,
  'breakfast'::meal_type,
  8,
  ARRAY['salé', 'oméga-3', 'méditerranéen'],
  '[{"name":"pain de seigle ou complet","qty":"2","unit":"tranches"},{"name":"sardines à l''huile d''olive","qty":"1","unit":"boîte"},{"name":"avocat","qty":"0.5","unit":"pièce"},{"name":"câpres","qty":"1","unit":"c. à soupe"},{"name":"citron (jus)","qty":"0.5","unit":"pièce"},{"name":"poivre, aneth","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Toaster le pain. Écraser l''avocat avec le jus de citron."},{"step":2,"text":"Étaler l''avocat sur le pain. Émietter les sardines par-dessus."},{"step":3,"text":"Parsemer de câpres, poivre et aneth. Servir immédiatement."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  'f7570199-cfc3-4811-8b6d-c049ca138a28'::uuid,
  'Porridge de sarrasin aux poires',
  'Porridge sans gluten et sans avoine, doux et légèrement noisette',
  'food'::day_type,
  'breakfast'::meal_type,
  15,
  ARRAY['sans gluten', 'noisette', 'hiver'],
  '[{"name":"grains de sarrasin","qty":"80","unit":"g"},{"name":"lait végétal","qty":"300","unit":"mL"},{"name":"poire","qty":"1","unit":"pièce"},{"name":"cannelle","qty":"1","unit":"c. à café"},{"name":"amandes effilées","qty":"1","unit":"c. à soupe"},{"name":"miel","qty":"1","unit":"c. à café"}]'::jsonb,
  '[{"step":1,"text":"Rincer le sarrasin. Le cuire dans le lait végétal à feu doux 12 min en remuant."},{"step":2,"text":"Couper la poire en fines lamelles. Faire revenir 2 min à sec dans une poêle avec la cannelle."},{"step":3,"text":"Verser le porridge dans un bol. Garnir de poire caramélisée, amandes et miel."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  'd744ebd3-cce0-47e2-87eb-38f5c23eb5e5'::uuid,
  'Shakshuka légère aux épinards',
  'Œufs pochés dans une sauce tomate épicée, version verte aux épinards',
  'food'::day_type,
  'breakfast'::meal_type,
  20,
  ARRAY['œufs', 'méditerranéen', 'épicé'],
  '[{"name":"œufs","qty":"4","unit":"pièces"},{"name":"épinards frais","qty":"200","unit":"g"},{"name":"tomates concassées en boîte","qty":"400","unit":"g"},{"name":"oignon","qty":"1","unit":"pièce"},{"name":"ail","qty":"2","unit":"gousses"},{"name":"cumin","qty":"1","unit":"c. à café"},{"name":"paprika fumé","qty":"0.5","unit":"c. à café"},{"name":"huile d''olive","qty":"1","unit":"c. à soupe"},{"name":"sel, poivre, piment doux","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Faire revenir oignon et ail dans l''huile. Ajouter épices 1 min."},{"step":2,"text":"Ajouter tomates et épinards. Laisser mijoter 8 min jusqu''à réduction."},{"step":3,"text":"Creuser 4 puits dans la sauce. Casser un œuf dans chaque. Couvrir et cuire 4-5 min. Servir avec du pain pita."}]'::jsonb,
  'essential'::plan_tier,
  true
),
(
  '595dcf20-6ec2-4e2f-8cda-1d05813316c9'::uuid,
  'Bowl protéiné fromage blanc-graines-pomme',
  'Bowl express très protéiné, idéal après une séance de sport matinale',
  'food'::day_type,
  'breakfast'::meal_type,
  5,
  ARRAY['protéiné', 'express', 'sport'],
  '[{"name":"fromage blanc 0% ou 20%","qty":"200","unit":"g"},{"name":"pomme","qty":"1","unit":"pièce"},{"name":"graines de lin","qty":"1","unit":"c. à soupe"},{"name":"graines de tournesol","qty":"1","unit":"c. à soupe"},{"name":"miel ou sirop d''érable","qty":"1","unit":"c. à café"},{"name":"cannelle","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Verser le fromage blanc dans un bol."},{"step":2,"text":"Râper ou trancher finement la pomme et déposer sur le fromage blanc."},{"step":3,"text":"Parsemer de graines, arroser de miel et saupoudrer de cannelle."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '26189c8d-122c-4e8b-81ac-b8b076ca444d'::uuid,
  'Crêpes légères sarrasin-pomme',
  'Crêpes fines et rustiques à la farine de sarrasin, garnies de compote maison',
  'food'::day_type,
  'breakfast'::meal_type,
  25,
  ARRAY['sans gluten', 'crêpes', 'weekend'],
  '[{"name":"farine de sarrasin","qty":"100","unit":"g"},{"name":"œuf","qty":"1","unit":"pièce"},{"name":"lait végétal","qty":"250","unit":"mL"},{"name":"sel","qty":"1","unit":"pincée"},{"name":"pommes pour la compote","qty":"2","unit":"pièces"},{"name":"cannelle","qty":"1","unit":"c. à café"},{"name":"huile de coco pour cuisson","qty":"1","unit":"c. à soupe"}]'::jsonb,
  '[{"step":1,"text":"Mélanger farine, œuf, lait et sel. Laisser reposer 10 min."},{"step":2,"text":"Peler et couper les pommes. Cuire à feu doux avec la cannelle et un peu d''eau 10 min. Écraser à la fourchette."},{"step":3,"text":"Cuire les crêpes dans une poêle huilée. Servir garnies de compote tiède."}]'::jsonb,
  'essential'::plan_tier,
  true
),
(
  '59b1e7f3-4ab6-4694-83bd-4f84a056a0db'::uuid,
  'Taboulé libanais quinoa-herbes',
  'Taboulé revisité au quinoa, frais et très herbacé comme au Liban',
  'food'::day_type,
  'lunch'::meal_type,
  20,
  ARRAY['libanais', 'frais', 'herbes'],
  '[{"name":"quinoa","qty":"80","unit":"g"},{"name":"persil plat","qty":"1","unit":"bouquet"},{"name":"menthe fraîche","qty":"0.5","unit":"bouquet"},{"name":"tomates","qty":"3","unit":"pièces"},{"name":"concombre","qty":"0.5","unit":"pièce"},{"name":"huile d''olive","qty":"2","unit":"c. à soupe"},{"name":"citron (jus)","qty":"1","unit":"pièce"},{"name":"sel, poivre, cumin","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Cuire le quinoa, rincer à l''eau froide et bien égoutter."},{"step":2,"text":"Hacher finement le persil et la menthe. Couper tomates et concombre en tout petits dés."},{"step":3,"text":"Mélanger tous les ingrédients. Assaisonner huile, citron, sel et cumin. Réfrigérer 20 min avant de servir."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '8add88a0-2471-4133-8f10-0e0484a3d964'::uuid,
  'Buddha bowl pois chiches rôtis-tahini',
  'Bowl vegan complet avec pois chiches croustillants et sauce tahini citronnée',
  'food'::day_type,
  'lunch'::meal_type,
  30,
  ARRAY['vegan', 'croustillant', 'complet'],
  '[{"name":"pois chiches cuits","qty":"200","unit":"g"},{"name":"riz brun ou millet","qty":"80","unit":"g"},{"name":"carotte râpée","qty":"1","unit":"pièce"},{"name":"chou rouge émincé","qty":"100","unit":"g"},{"name":"avocat","qty":"1","unit":"avocat"},{"name":"tahini","qty":"2","unit":"c. à soupe"},{"name":"citron (jus)","qty":"1","unit":"pièce"},{"name":"cumin","qty":"1","unit":"c. à café"},{"name":"huile d''olive","qty":"1","unit":"c. à soupe"}]'::jsonb,
  '[{"step":1,"text":"Préchauffer le four à 200°C. Mélanger pois chiches, huile et cumin. Rôtir 25 min jusqu''à croustillants."},{"step":2,"text":"Cuire le riz ou millet. Préparer la sauce : tahini + citron + 3 c. à soupe d''eau."},{"step":3,"text":"Assembler le bowl : céréale, légumes crus, pois chiches. Arroser de sauce tahini."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '7a467961-8804-4963-8694-6c4660a054ab'::uuid,
  'Soupe minestrone légère',
  'Soupe italienne de légumes de saison, sans pâtes, très complète',
  'food'::day_type,
  'lunch'::meal_type,
  35,
  ARRAY['italien', 'soupe', 'légumes'],
  '[{"name":"courgette","qty":"1","unit":"pièce"},{"name":"carottes","qty":"2","unit":"pièces"},{"name":"haricots verts","qty":"100","unit":"g"},{"name":"haricots blancs cuits","qty":"100","unit":"g"},{"name":"tomates concassées","qty":"400","unit":"g"},{"name":"bouillon de légumes","qty":"1","unit":"L"},{"name":"oignon","qty":"1","unit":"pièce"},{"name":"ail","qty":"2","unit":"gousses"},{"name":"huile d''olive","qty":"1","unit":"c. à soupe"},{"name":"thym, laurier, sel, poivre","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Faire revenir oignon et ail dans l''huile. Ajouter carottes en rondelles."},{"step":2,"text":"Ajouter courgette, haricots verts, tomates et bouillon. Cuire 20 min."},{"step":3,"text":"Incorporer les haricots blancs les 5 dernières minutes. Assaisonner. Servir avec un filet d''huile d''olive."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '37345d58-6b9e-43e0-83e8-badbde729732'::uuid,
  'Salade niçoise revisitée',
  'La niçoise allégée avec thon, œufs et légumes croquants',
  'food'::day_type,
  'lunch'::meal_type,
  20,
  ARRAY['provençal', 'équilibré', 'protéiné'],
  '[{"name":"thon au naturel","qty":"1","unit":"boîte"},{"name":"œufs","qty":"2","unit":"pièces"},{"name":"haricots verts","qty":"150","unit":"g"},{"name":"tomates cerises","qty":"10","unit":"pièces"},{"name":"concombre","qty":"0.5","unit":"pièce"},{"name":"olives noires","qty":"8","unit":"pièces"},{"name":"huile d''olive","qty":"2","unit":"c. à soupe"},{"name":"vinaigre de vin","qty":"1","unit":"c. à soupe"},{"name":"sel, poivre, moutarde","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Cuire les œufs 9 min (durs). Blanchir les haricots verts 5 min, rafraîchir à l''eau froide."},{"step":2,"text":"Disposer mesclun, thon, haricots, tomates, concombre, olives dans un bol."},{"step":3,"text":"Préparer la vinaigrette : huile, vinaigre, moutarde, sel, poivre. Verser et mélanger."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  'f9aa94da-6da1-47f0-8c5a-24a16c1db83b'::uuid,
  'Galettes de courgette-chèvre',
  'Galettes légères à la poêle, croustillantes dehors et fondantes dedans',
  'food'::day_type,
  'lunch'::meal_type,
  20,
  ARRAY['végétarien', 'croustillant', 'rapide'],
  '[{"name":"courgettes","qty":"2","unit":"pièces"},{"name":"œufs","qty":"2","unit":"pièces"},{"name":"farine complète","qty":"50","unit":"g"},{"name":"chèvre frais","qty":"60","unit":"g"},{"name":"menthe fraîche hachée","qty":"1","unit":"c. à soupe"},{"name":"huile d''olive","qty":"1","unit":"c. à soupe"},{"name":"sel, poivre","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Râper les courgettes. Presser dans un torchon pour enlever l''excès d''eau."},{"step":2,"text":"Mélanger courgettes, œufs, farine, chèvre émietté, menthe, sel et poivre."},{"step":3,"text":"Faire des galettes dans une poêle huilée. Cuire 3-4 min de chaque côté jusqu''à dorées."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  'cdcafebc-12b5-4dfb-8710-8bf5467829f2'::uuid,
  'Soupe de pois cassés-lard maigre',
  'Soupe roborative et saine, façon grand-mère allégée',
  'food'::day_type,
  'lunch'::meal_type,
  50,
  ARRAY['réconfortant', 'fibres', 'hiver'],
  '[{"name":"pois cassés jaunes","qty":"200","unit":"g"},{"name":"carotte","qty":"1","unit":"pièce"},{"name":"oignon","qty":"1","unit":"pièce"},{"name":"lard maigre fumé","qty":"1","unit":"tranche"},{"name":"bouillon de légumes","qty":"1","unit":"L"},{"name":"ail","qty":"2","unit":"gousses"},{"name":"thym, sel, poivre","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Rincer les pois cassés. Faire revenir oignon, ail et lard en petits dés."},{"step":2,"text":"Ajouter carottes, pois cassés, thym et bouillon. Cuire 40 min à feu doux."},{"step":3,"text":"Mixer partiellement pour une texture crémeuse mais pas lisse. Rectifier l''assaisonnement."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  'b5a3b714-ea7c-453c-8d2b-99237e772fc6'::uuid,
  'Poke bowl thon-mangue-edamame',
  'Bowl hawaïen frais, coloré et équilibré, prêt en 15 minutes',
  'food'::day_type,
  'lunch'::meal_type,
  15,
  ARRAY['hawaïen', 'frais', 'coloré'],
  '[{"name":"thon frais qualité sashimi","qty":"150","unit":"g"},{"name":"riz à sushi cuit et refroidi","qty":"80","unit":"g"},{"name":"edamame (fèves de soja) décortiqués","qty":"80","unit":"g"},{"name":"mangue fraîche en dés","qty":"80","unit":"g"},{"name":"avocat","qty":"0.5","unit":"pièce"},{"name":"sauce tamari","qty":"1","unit":"c. à soupe"},{"name":"huile de sésame","qty":"1","unit":"c. à café"},{"name":"graines de sésame","qty":"1","unit":"c. à café"},{"name":"citron vert","qty":"0.5","unit":"pièce"}]'::jsonb,
  '[{"step":1,"text":"Couper le thon en dés. Mélanger avec tamari et huile de sésame. Mariner 5 min."},{"step":2,"text":"Déposer le riz dans un bol. Disposer thon, edamame, mangue et avocat en sections."},{"step":3,"text":"Arroser du reste de marinade. Parsemer de sésame. Servir avec le citron vert."}]'::jsonb,
  'essential'::plan_tier,
  true
),
(
  '6b09c2ef-8e19-4e49-83b8-49923c18c9c3'::uuid,
  'Lentilles tièdes vinaigrette-dijon',
  'Lentilles vertes du Puy tièdes avec une vinaigrette moutardée classique',
  'food'::day_type,
  'lunch'::meal_type,
  30,
  ARRAY['légumineuses', 'français', 'fibres'],
  '[{"name":"lentilles vertes du Puy","qty":"150","unit":"g"},{"name":"carotte","qty":"1","unit":"pièce"},{"name":"échalote","qty":"1","unit":"pièce"},{"name":"huile d''olive","qty":"2","unit":"c. à soupe"},{"name":"vinaigre de vin rouge","qty":"1","unit":"c. à soupe"},{"name":"moutarde de Dijon","qty":"1","unit":"c. à café"},{"name":"persil plat","qty":"1","unit":"bouquet"},{"name":"sel, poivre","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Cuire les lentilles avec la carotte en dés dans de l''eau non salée 25 min. Égoutter."},{"step":2,"text":"Préparer la vinaigrette : huile, vinaigre, moutarde, sel, poivre. Fouetter."},{"step":3,"text":"Mélanger lentilles tièdes, échalote émincée et vinaigrette. Parsemer de persil."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  'd9d91d65-deaf-467b-8910-f92ae2cf821d'::uuid,
  'Sandwich club poulet-avocat allégé',
  'Sandwich généreux avec du poulet grillé maison et sans mayonnaise',
  'food'::day_type,
  'lunch'::meal_type,
  15,
  ARRAY['portable', 'protéiné', 'sans mayo'],
  '[{"name":"pain complet","qty":"3","unit":"tranches"},{"name":"filet de poulet grillé","qty":"120","unit":"g"},{"name":"avocat","qty":"0.5","unit":"pièce"},{"name":"tomates en rondelles","qty":"2","unit":"pièces"},{"name":"laitue","qty":"2","unit":"feuilles"},{"name":"yaourt grec mélangé à une c. à café de moutarde","qty":"1","unit":"c. à soupe"},{"name":"sel, poivre","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Toaster le pain. Écraser l''avocat avec sel et poivre."},{"step":2,"text":"Étaler le yaourt-moutarde sur une tranche, l''avocat sur une autre."},{"step":3,"text":"Assembler : pain / laitue+tomate / pain / poulet+avocat / pain. Piquer avec un cure-dents et couper en diagonale."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  'c776af4c-864b-449d-892a-a1dfca3a0c43'::uuid,
  'Rösti de patate douce-herbes',
  'Galette croustillante de patate douce, servie avec crème légère à l''aneth',
  'food'::day_type,
  'lunch'::meal_type,
  25,
  ARRAY['végétarien', 'croustillant', 'original'],
  '[{"name":"patate douce","qty":"300","unit":"g"},{"name":"œuf","qty":"1","unit":"pièce"},{"name":"farine complète","qty":"2","unit":"c. à soupe"},{"name":"ciboulette ciselée","qty":"1","unit":"c. à soupe"},{"name":"yaourt grec","qty":"100","unit":"g"},{"name":"aneth frais","qty":"1","unit":"c. à soupe"},{"name":"huile d''olive","qty":"1","unit":"c. à soupe"},{"name":"sel, poivre, muscade","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Râper la patate douce. Presser dans un torchon. Mélanger avec œuf, farine, ciboulette, sel, muscade."},{"step":2,"text":"Former des galettes. Cuire à la poêle huilée 5 min de chaque côté."},{"step":3,"text":"Mélanger yaourt et aneth. Servir les rösti avec la crème fraîche à l''aneth."}]'::jsonb,
  'essential'::plan_tier,
  true
),
(
  'dd740151-4252-470f-8b67-6ad21fbbd1b8'::uuid,
  'Velouté brocoli-chèvre',
  'Velouté vert intense et crémeux sans crème, avec une touche de chèvre frais',
  'food'::day_type,
  'dinner'::meal_type,
  25,
  ARRAY['velouté', 'végétarien', 'vert'],
  '[{"name":"brocoli","qty":"500","unit":"g"},{"name":"oignon","qty":"1","unit":"pièce"},{"name":"bouillon de légumes","qty":"600","unit":"mL"},{"name":"chèvre frais","qty":"60","unit":"g"},{"name":"huile d''olive","qty":"1","unit":"c. à soupe"},{"name":"sel, poivre, muscade","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Faire revenir l''oignon dans l''huile 3 min. Ajouter le brocoli en fleurettes et le bouillon."},{"step":2,"text":"Cuire 15 min à feu moyen. Mixer finement avec le chèvre."},{"step":3,"text":"Assaisonner avec sel, poivre et muscade. Servir avec un filet d''huile d''olive."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '32b77354-dcb9-440a-81cc-4fd92d3ac1de'::uuid,
  'Dahl de lentilles corail-tomate',
  'Dahl indien doux et réconfortant, vegan et prêt en 30 minutes',
  'food'::day_type,
  'dinner'::meal_type,
  30,
  ARRAY['indien', 'vegan', 'réconfortant'],
  '[{"name":"lentilles corail","qty":"150","unit":"g"},{"name":"tomates concassées","qty":"400","unit":"g"},{"name":"bouillon de légumes","qty":"400","unit":"mL"},{"name":"oignon","qty":"1","unit":"pièce"},{"name":"ail","qty":"3","unit":"gousses"},{"name":"curcuma","qty":"1","unit":"c. à café"},{"name":"garam masala","qty":"1","unit":"c. à café"},{"name":"cumin","qty":"1","unit":"c. à café"},{"name":"huile de coco","qty":"1","unit":"c. à soupe"},{"name":"coriandre fraîche","qty":"1","unit":"bouquet"}]'::jsonb,
  '[{"step":1,"text":"Faire revenir oignon et ail dans l''huile de coco. Ajouter les épices 1 min."},{"step":2,"text":"Ajouter lentilles rincées, tomates et bouillon. Cuire 25 min en remuant."},{"step":3,"text":"Servir avec du riz basmati et de la coriandre fraîche."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  'e9ac4d02-b59d-4d82-8b48-64249afef7b0'::uuid,
  'Filet de truite amande-citron',
  'Truite poêlée en moins de 15 minutes, avec beurre d''amandes doré',
  'food'::day_type,
  'dinner'::meal_type,
  15,
  ARRAY['poisson', 'rapide', 'élégant'],
  '[{"name":"filets de truite","qty":"2","unit":"pièces"},{"name":"amandes effilées","qty":"30","unit":"g"},{"name":"beurre","qty":"1","unit":"c. à soupe"},{"name":"citron","qty":"1","unit":"pièce"},{"name":"persil plat","qty":"1","unit":"bouquet"},{"name":"sel, poivre, fleur de sel","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Assaisonner les filets. Cuire côté peau dans une poêle chaude 4-5 min. Retourner 2 min."},{"step":2,"text":"Dans la même poêle, faire dorer le beurre et les amandes 2 min jusqu''à coloration noisette."},{"step":3,"text":"Napper les filets de beurre aux amandes. Finir avec persil et citron."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '0975a9b7-8ddc-4947-85b9-e31d6383a6c7'::uuid,
  'Tajine de légumes-pois chiches',
  'Tajine vegan parfumé aux épices douces du Maghreb',
  'food'::day_type,
  'dinner'::meal_type,
  40,
  ARRAY['maghrébin', 'vegan', 'épicé doux'],
  '[{"name":"pois chiches cuits","qty":"400","unit":"g"},{"name":"carottes","qty":"2","unit":"pièces"},{"name":"courgette","qty":"1","unit":"pièce"},{"name":"courge butternut","qty":"200","unit":"g"},{"name":"tomates concassées","qty":"400","unit":"g"},{"name":"oignon","qty":"1","unit":"pièce"},{"name":"ras-el-hanout","qty":"1","unit":"c. à café"},{"name":"cannelle","qty":"1","unit":"c. à café"},{"name":"miel","qty":"1","unit":"c. à soupe"},{"name":"huile d''olive","qty":"1","unit":"c. à soupe"},{"name":"coriandre","qty":"1","unit":"bouquet"}]'::jsonb,
  '[{"step":1,"text":"Faire revenir oignon et épices dans l''huile 2 min."},{"step":2,"text":"Ajouter légumes en morceaux, tomates et miel. Couvrir et cuire 30 min à feu doux."},{"step":3,"text":"Incorporer les pois chiches les 10 dernières minutes. Servir avec couscous et coriandre fraîche."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '9daa32f4-b890-4278-8acd-4891e76721ee'::uuid,
  'Steak de chou-fleur rôti-chimichurri',
  'Steak végétal impressionnant, caramélisé au four avec une sauce herbacée vive',
  'food'::day_type,
  'dinner'::meal_type,
  35,
  ARRAY['vegan', 'original', 'four'],
  '[{"name":"chou-fleur (en tranches épaisses de 2cm)","qty":"1","unit":"pièce"},{"name":"huile d''olive","qty":"3","unit":"c. à soupe"},{"name":"cumin, paprika, sel","qty":"0","unit":"pincée"},{"name":"persil","qty":"1","unit":"bouquet"},{"name":"ail","qty":"1","unit":"gousse"},{"name":"vinaigre de vin rouge","qty":"2","unit":"c. à soupe"},{"name":"piment rouge séché","qty":"1","unit":"pincée"},{"name":"huile d''olive pour chimichurri","qty":"2","unit":"c. à soupe"}]'::jsonb,
  '[{"step":1,"text":"Préchauffer le four à 220°C. Badigeonner les steaks de chou-fleur d''huile, cumin, paprika et sel."},{"step":2,"text":"Rôtir 25 min en retournant à mi-cuisson jusqu''à caramélisation."},{"step":3,"text":"Mixer persil, ail, vinaigre, piment et huile pour le chimichurri. Servir les steaks nappés de sauce."}]'::jsonb,
  'essential'::plan_tier,
  true
),
(
  '973cd89e-f268-4082-8a74-d45d2ea15c3b'::uuid,
  'Maquereaux grillés-pommes de terre vapeur',
  'Poisson gras accessible et économique, à la plancha ou au four',
  'food'::day_type,
  'dinner'::meal_type,
  25,
  ARRAY['oméga-3', 'économique', 'simple'],
  '[{"name":"filets de maquereau","qty":"2","unit":"pièces"},{"name":"pommes de terre","qty":"300","unit":"g"},{"name":"citron","qty":"1","unit":"pièce"},{"name":"moutarde à l''ancienne","qty":"1","unit":"c. à soupe"},{"name":"huile d''olive","qty":"1","unit":"c. à soupe"},{"name":"sel, poivre, ciboulette","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Cuire les pommes de terre à la vapeur 20 min."},{"step":2,"text":"Badigeonner les filets de moutarde et huile. Griller 4 min de chaque côté."},{"step":3,"text":"Servir le maquereau avec les pommes de terre, le citron et la ciboulette."}]'::jsonb,
  'starter'::plan_tier,
  true
),
(
  '61fb6c27-c7f5-48d7-8a45-41a0303d851d'::uuid,
  'Aubergines farcies riz-herbes-tomate',
  'Aubergines confites farcies d''un riz aux herbes, végétarien et généreux',
  'food'::day_type,
  'dinner'::meal_type,
  45,
  ARRAY['végétarien', 'farci', 'méditerranéen'],
  '[{"name":"aubergines","qty":"2","unit":"pièces"},{"name":"riz basmati","qty":"80","unit":"g"},{"name":"tomates","qty":"2","unit":"pièces"},{"name":"oignon","qty":"1","unit":"pièce"},{"name":"menthe fraîche","qty":"1","unit":"c. à soupe"},{"name":"persil","qty":"1","unit":"c. à soupe"},{"name":"huile d''olive","qty":"2","unit":"c. à soupe"},{"name":"parmesan râpé","qty":"30","unit":"g"},{"name":"sel, poivre, cannelle","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Couper les aubergines en 2. Creuser la chair et la faire revenir avec l''oignon, les tomates et les épices."},{"step":2,"text":"Cuire le riz. Mélanger avec la farce de légumes et les herbes."},{"step":3,"text":"Farcir les aubergines. Parsemer de parmesan. Cuire au four à 180°C pendant 30 min."}]'::jsonb,
  'essential'::plan_tier,
  true
),
(
  '6be62678-8bde-4365-8ebe-74a6c57563f8'::uuid,
  'Filet mignon de porc aux pommes',
  'Filet mignon tendre aux pommes caramélisées, version légère sans crème',
  'food'::day_type,
  'dinner'::meal_type,
  30,
  ARRAY['viande blanche', 'pommes', 'festif'],
  '[{"name":"filet mignon de porc","qty":"300","unit":"g"},{"name":"pommes","qty":"2","unit":"pièces"},{"name":"miel","qty":"1","unit":"c. à soupe"},{"name":"cidre brut","qty":"100","unit":"mL"},{"name":"thym","qty":"1","unit":"branche"},{"name":"huile d''olive","qty":"1","unit":"c. à soupe"},{"name":"sel, poivre","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Couper le filet en médaillons. Saisir dans l''huile chaude 2 min de chaque côté. Réserver."},{"step":2,"text":"Dans la même poêle, faire caraméliser les pommes en quartiers avec le miel."},{"step":3,"text":"Déglacer au cidre, remettre le porc, ajouter le thym. Cuire 10 min à couvert à feu doux."}]'::jsonb,
  'essential'::plan_tier,
  true
),
(
  'ae986dff-3a20-426a-8300-a0c076e76f09'::uuid,
  'Risotto de chou-fleur-citron',
  'Faux risotto vegan à base de chou-fleur mixé, léger et crémeux',
  'food'::day_type,
  'dinner'::meal_type,
  20,
  ARRAY['vegan', 'léger', 'original'],
  '[{"name":"chou-fleur","qty":"1","unit":"pièce"},{"name":"citron (zeste + jus)","qty":"1","unit":"pièce"},{"name":"ail","qty":"2","unit":"gousses"},{"name":"bouillon de légumes chaud","qty":"200","unit":"mL"},{"name":"levure nutritionnelle","qty":"2","unit":"c. à soupe"},{"name":"huile d''olive","qty":"1","unit":"c. à soupe"},{"name":"persil","qty":"1","unit":"bouquet"},{"name":"sel, poivre","qty":"0","unit":"pincée"}]'::jsonb,
  '[{"step":1,"text":"Mixer le chou-fleur cru en petits grains (texture riz grossier)."},{"step":2,"text":"Faire revenir l''ail dans l''huile. Ajouter le chou-fleur mixé et le bouillon petit à petit en remuant."},{"step":3,"text":"Cuire 8 min à feu moyen. Incorporer levure nutritionnelle, zeste de citron et persil."}]'::jsonb,
  'essential'::plan_tier,
  true
),
(
  '66d3a68b-7399-49ac-8fc6-c4ee3c0e4910'::uuid,
  'Soupe pho de bœuf léger',
  'Pho vietnamien allégé avec un bouillon aromatique maison et des légumes croquants',
  'food'::day_type,
  'dinner'::meal_type,
  45,
  ARRAY['vietnamien', 'soupe', 'réconfortant'],
  '[{"name":"nouilles de riz plates","qty":"100","unit":"g"},{"name":"bouillon de bœuf","qty":"800","unit":"mL"},{"name":"bœuf tranché finement (rumsteck)","qty":"150","unit":"g"},{"name":"étoiles de badiane","qty":"2","unit":"pièces"},{"name":"cannelle","qty":"1","unit":"bâton"},{"name":"gingembre","qty":"3","unit":"tranches"},{"name":"germes de soja","qty":"100","unit":"g"},{"name":"oignons verts","qty":"2","unit":"pièces"},{"name":"coriandre et basilic thaï","qty":"1","unit":"bouquet"},{"name":"citron vert","qty":"1","unit":"pièce"},{"name":"sauce poisson (nuoc-mâm)","qty":"1","unit":"c. à soupe"}]'::jsonb,
  '[{"step":1,"text":"Faire chauffer le bouillon avec badiane, cannelle, gingembre et nuoc-mâm. Infuser 20 min. Filtrer."},{"step":2,"text":"Cuire les nouilles à part. Les répartir dans des bols."},{"step":3,"text":"Verser le bouillon bouillant sur le bœuf cru tranché (il cuit dans le bouillon). Garnir de germes de soja, oignons verts, herbes et citron vert."}]'::jsonb,
  'essential'::plan_tier,
  true
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  day_type = EXCLUDED.day_type,
  meal_type = EXCLUDED.meal_type,
  duration_min = EXCLUDED.duration_min,
  tags = EXCLUDED.tags,
  ingredients = EXCLUDED.ingredients,
  steps = EXCLUDED.steps,
  plan_required = EXCLUDED.plan_required,
  published = EXCLUDED.published;
